'''function to count the number of words in a string'''
def count_words(string):
    '''function to count the number of words in a string'''
    return len(string.split())

#calling the function
sent = '''
Nesse paper pretendo analisar as características de interfaces gráficas e acervos de fontes digitalizadas brasieliras e avaliar caminhos possíveis para percorrer a longa estrada que separa a coleta do documento digitalizado até sua transformação em um texto capaz de ser analisado como dado no Brasil.

Para tanto tomarei como exemplo a interface gráfica e o acervo da Hemeroteca Digital Brasileira, que faz parte da Fundação Biblioteca Nacional, e a pyHDB, uma ferramenta heurística desenvolvida em Python especificamente para pesquisa, coleta e organização dos dados da Hemeroteca Digital Brasileira. A pyHDB utiliza técnicas de web scraping e tem como objetivo auxiliar pesquisadores no processo de construção e registro metodológico, gerando relatórios e fornecendo dados tabulares e data sets de imagens a partir dos parâmetros de busca definidos pelo usuário. A partir da análise desse caso, busco apresentar um conjunto de possibilidades para analisar o acervo da Hemeroteca Digital Brasileira e avançar na transformação dos dados brutos para texto legível por computador. Serão apresentadas formas de analisar os metadados organizados pela pyHDB com Pandas e Plotly e o tratamento das imagens digitalizadas com conjuntos de ferramentas para reconhecimento de layout e caracteres, como LayoutParser, OCR-d, gImageReader e Transkribus.

Portanto, esse paper pretender discutir as limitações, desafios e caminhos possíveis para a elaboração de pesquisas em humanidades digitais que pretendem trabalhar com texto como data a partir de conjuntos de fontes primárias digitalizadas. É cada vez mais comum a disponibilização online de tais documentos por instituições brasileiras, como a Biblioteca Digital do Senado Federal (BDSF), com acervo referente ao poder legislativo; o Acervo Histórico do Diário Oficial da União - DOU, mantido pela Imprensa Nacional, com o acervo digitalizado entre 1808 e 2001 e a supracitada Hemeroteca Digital Brasileira, que compõe a BNDigital, projeto da Fundação Biblioteca Nacional que reúne milhões de páginas digitalizadas. A Hemeroteca Digital Brasileira tem se mostrado como um marco na pesquisa histórica, sobretudo em recortes sobre os séculos XIX e XX, seja pelo seu vasto acervo digitalizado de jornais de todo o país e de outros lugares do mundo, seja pelo motor de busca por palavras. Em geral, esses acervos apresentam interfaces gráficas de usuário que permitem buscas por parâmetros simples (data, autoria, assuntos, publicações, etc), com exceção da HDB que possui busca por palavras no corpo dos documentos, e retornam listas de resultados para os usuários permitindo o download de páginas em PDF ou variados formatos de imagens. Entretanto, não existem recursos para acesso ao próprio texto do documento, ou dados sobre precisão de OCR, frequência de palavras, possibilidade de download em massa ou ainda a geração de relatórios sobre as buscas e resultados.

Assim, apesar da importância e crescimento do processo de digitalização e disponibilização dos acervos de forma aberta, o caráter desses acervos e interfaces gráficas, de suas ferramentas de busca e tipos de resultados retornados aos usuários limita e muitas vezes coloca empecilhos quase intransponíveis para aqueles que desejam aplicar métodos de análise de texto como dado.
'''
print(count_words(sent))